name: windows_installer_msix_dertificate
description: A new Flutter project.

 
publish_to: 'none'  


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^1.0.0

  # required package
  msix: ^3.0.0-dev.1
 
flutter:
 
  uses-material-design: true

msix_config:
  publisher: CN=Blackshadow
  display_name: Blackshadow
  publisher_display_name: Blackshadow
  identity_name: MyCompany.MySuite.MyApp
  msix_version: 1.0.0.0
  logo_path: G:\Windows-Installer-with-NSIX-and-Certificate\assets\utils\logo.png
  certificate_path: G:\Windows-Installer-with-NSIX-and-Certificate\assets\utils\cert.pfx
  certificate_password: 1234 